### PR TITLE
Create .npmignore

### PR DESCRIPTION
**Pull request by CristianDuta**
Add tests to npm ignore list

### CODE REVIEW

**Review by eddyerburgh — APPROVED** [review]
👍

**Comment by CristianDuta** [comment]
Hi there,

Is there any way you can publish the latest changes to npm?
I really appreciate this!

Thank you,
Cristian

**Comment by eddyerburgh** [comment]
Sure Christian, I've just published it in 2.0.1 😃

**Comment by eddyerburgh** [comment]
Out of interest, why was having the test directory causing problems?

**Comment by CristianDuta** [comment]
Perfect!
Thank you very much! <3

**Comment by CristianDuta** [comment]
I'm trying to write unittests in a meteor project and the tests from this package were being run at 'server' level which was causing compilation errors.

**Pull request merged**
